
biome_block_choice = {"minecraft:plains": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:meadow": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:dark_forest": {"log":"dark_oak_log",
                                           "plank":"dark_oak_plank",
                                           "fence":"dark_oak_fence",
                                           "stairs":"dark_oak_stairs",
                                           "slab":"dark_oak_slab",
                                           "door":"dark_oak_door",
                                           "leaves":"dark_oak_leaves",},
                      "minecraft:ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:deep_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:warm_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:luke_warm_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:deep_luke_warm_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:cold_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:deep_cold_ocean": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:frozen_ocean": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:deep_frozen_ocean": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:mushroom_fields": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:jagged_peaks": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:frozen_peaks": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:stony_peaks": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:cherry_grove": {"log":"cherry_log",
                                           "plank":"cherry_planks",
                                           "fence":"cherry_fence",
                                           "stairs":"cherry_stairs",
                                           "slab":"cherry_slab",
                                           "door":"cherry_door",
                                           "leaves":"cherry_leaves"},
                      "minecraft:grove": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:snowy_slopes": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:windswept_hills": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:windswept_gravelly_hills": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:windswept_forest": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:forest": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:flower_forest": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:taiga": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:old_growth_pine_taiga": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:old_growth_spruce_taiga": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:snowy_taiga": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:birch_forest": {"log":"birch_log",
                                           "plank":"birch_planks",
                                           "fence":"birch_fence",
                                           "stairs":"birch_stairs",
                                           "slab":"birch_slab",
                                           "door":"birch_door",
                                           "leaves":"birch_leaves"},
                      "minecraft:old_growth_birch_forest": {"log":"birch_log",
                                           "plank":"birch_planks",
                                           "fence":"birch_fence",
                                           "stairs":"birch_stairs",
                                           "slab":"birch_slab",
                                           "door":"birch_door",
                                           "leaves":"birch_leaves"},
                      "minecraft:dark_forest": {"log":"dark_oak_log",
                                           "plank":"dark_oak_planks",
                                           "fence":"dark_oak_fence",
                                           "stairs":"dark_oak_stairs",
                                           "slab":"dark_oak_slab",
                                           "door":"dark_oak_door",
                                           "leaves":"dark_oak_leaves"},
                      "minecraft:jungle": {"log":"jungle_log",
                                           "plank":"jungle_planks",
                                           "fence":"jungle_fence",
                                           "stairs":"jungle_stairs",
                                           "slab":"jungle_slab",
                                           "door":"jungle_door",
                                           "leaves":"jungle_leaves"},
                      "minecraft:sparse_jungle": {"log":"jungle_log",
                                           "plank":"jungle_planks",
                                           "fence":"jungle_fence",
                                           "stairs":"jungle_stairs",
                                           "slab":"jungle_slab",
                                           "door":"jungle_door",
                                           "leaves":"jungle_leaves"},
                      "minecraft:bamboo_jungle": {"log":"jungle_log",
                                           "plank":"jungle_planks",
                                           "fence":"jungle_fence",
                                           "stairs":"jungle_stairs",
                                           "slab":"jungle_slab",
                                           "door":"jungle_door",
                                           "leaves":"jungle_leaves"},
                      "minecraft:river": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:frozen_river": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:swamp": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:mangrove_swamp": {"log":"mangrove_log",
                                           "plank":"mangrove_planks",
                                           "fence":"mangrove_fence",
                                           "stairs":"mangrove_stairs",
                                           "slab":"mangrove_slab",
                                           "door":"mangrove_door",
                                           "leaves":"mangrove_leaves"},
                      "minecraft:beach": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:snowy_beach": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:stony_shore": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:sunflower_plains": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:snowy_plains": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:ice_spikes": {"log":"spruce_log",
                                           "plank":"spruce_planks",
                                           "fence":"spruce_fence",
                                           "stairs":"spruce_stairs",
                                           "slab":"spruce_slab",
                                           "door":"spruce_door",
                                           "leaves":"spruce_leaves"},
                      "minecraft:desert": {"log":"red_sandstone",
                                           "plank":"sandstone",
                                           "fence":"oak_fence",
                                           "stairs":"sandstone_stairs",
                                           "slab":"sandstone_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:savanna": {"log":"acacia_log",
                                           "plank":"acacia_planks",
                                           "fence":"acacia_fence",
                                           "stairs":"acacia_stairs",
                                           "slab":"acacia_slab",
                                           "door":"acacia_door",
                                           "leaves":"acacia_leaves"},
                      "minecraft:savanna_plateau": {"log":"acacia_log",
                                           "plank":"acacia_planks",
                                           "fence":"acacia_fence",
                                           "stairs":"acacia_stairs",
                                           "slab":"acacia_slab",
                                           "door":"acacia_door",
                                           "leaves":"acacia_leaves"},
                      "minecraft:windswept_savanna": {"log":"acacia_log",
                                           "plank":"acacia_planks",
                                           "fence":"acacia_fence",
                                           "stairs":"acacia_stairs",
                                           "slab":"acacia_slab",
                                           "door":"acacia_door",
                                           "leaves":"acacia_leaves"},
                      "minecraft:badlands": {"log":"dark_oak_log",
                                           "plank":"dark_oak_planks",
                                           "fence":"dark_oak_fence",
                                           "stairs":"dark_oak_stairs",
                                           "slab":"dark_oak_slab",
                                           "door":"dark_oak_door",
                                           "leaves":"dark_oak_leaves"},
                      "minecraft:wooded_badlands": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"},
                      "minecraft:eroded_badlands": {"log":"oak_log",
                                           "plank":"oak_planks",
                                           "fence":"oak_fence",
                                           "stairs":"oak_stairs",
                                           "slab":"oak_slab",
                                           "door":"oak_door",
                                           "leaves":"oak_leaves"}}
# print(worldSlice.getBiome(addY(buildRect.middle, heightmap[tuple(buildRect.offset)])))
